### Get default endpoint
GET http://localhost:3001

### Initialize DB
GET http://localhost:3001/init

### Get all scores
GET http://localhost:3001/list

### Limit result to 15
GET http://localhost:3001/list/15

### Order results by score
GET http://localhost:3001/bestScores

### Get results based on score
GET http://localhost:3001/getByScore/43